apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend
spec:
  selector: # which pods to manage under this deployment
    matchLabels:
      app: sa-frontend
  replicas: 2
  minReadySeconds: 15
  strategy: # deployment strategy
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template: # the pod template
    metadata:
      labels:
        app: sa-frontend                                 
    spec:                                                
      containers:
        - image: alabebop/sentiment-analysis-frontend-multistage
          imagePullPolicy: Always
          name: sa-frontend                              
          ports:
            # nginx port
            - containerPort: 80  