apiVersion: v1
kind: Pod                                            
metadata:
  name: sa-frontend
  labels:
    app: sa-frontend                                 
spec:                                                
  containers:
    - image: alabebop/sentiment-analysis-frontend-multistage
      name: sa-frontend                              
      ports:
        # nginx port
        - containerPort: 80                          