apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-web-app
  labels:
    app: sa-web-app
spec:
  selector:
    matchLabels:
      app: sa-web-app
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-web-app
    spec:
      containers:
      - image: alabebop/sentiment-analysis-webapp-multistage
        imagePullPolicy: Always
        name: sa-web-app
        env:
          - name: SA_LOGIC_URL
            value: "http://sa-logic"
            # value: "http://10.108.232.130"
          - name: SA_LOGIC_PORT
            value: "80"
          - name: SA_WEBAPP_PORT
            value: "8080"
        ports:
          - containerPort: 8080
