apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: ExternalName
  # local
  # externalName: host.docker.internal
  # RDS
  externalName: rds-eksworkshop.ckh6ob5pwvnv.ap-northeast-1.rds.amazonaws.com
  ports:
    - protocol: TCP
      port: 3306
      name: mysql
    - protocol: TCP
      port: 8000
      name: http


